module.exports.TEST_ADVERT = {
  productId: undefined,
  productName: "20V CORDLESS DRILL KIT",
  sku: "TEST-CIDLI20",
  primarySpecification: "2 x 2.0Ah BATTERIES + CHARGER",
  secondarySpecification: "Compact, powerful drilling and screwdriving kit",
  feature01: "20V POWER",
  feature02: "2 BATTERIES",
  keyBenefit: "IDEAL FOR DIY & TRADE",
  campaignType: "Back In Stock",
  campaignMessage: "BACK IN STOCK",
  sellingPrice: "2499",
  disclaimer: "WHILE STOCKS LAST",
  moodId: "thumbs_up",
  originalImageUrl: "",
  processedImageUrl: "",
  backgroundRemovalStatus: "PENDING",
  useOriginalImage: false,
  qrUrl: "https://www.toolhub.co.za",
};
