const test=require('node:test');const assert=require('node:assert/strict');
const {analyzePdfPage}=require('../.test-dist/lib/pdf-analysis');
const {heuristicPageAnalysis,coreReviewIssues}=require('../.test-dist/lib/pdf-import');
const {extractedPricing,resolvePricing,pricingInputSchema}=require('../.test-dist/lib/import-pricing');
const {advertSchema,TEST_ADVERT}=require('../.test-dist/lib/advert');
function pdf(lines){const text=lines.map(s=>'('+s.replace(/[()\\]/g,'\\$&')+') Tj T*').join('\n');const stream=`BT /F1 12 Tf 16 TL 40 750 Td ${text} ET`;const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 800] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let b='%PDF-1.4\n';const offsets=[];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(b));b+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(b);b+=`xref\n0 6\n0000000000 65535 f \n${offsets.map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Uint8Array(Buffer.from(b));}
async function read(lines){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const d=await pdfjs.getDocument({data:pdf(lines)}).promise;const content=await(await d.getPage(1)).getTextContent();return content.items.filter(i=>i.str).map(i=>i.str).join('\n');}
test('digital PDF: direct embedded facts and price preferred without OCR request',async()=>{let calls=0;const embeddedText=await read(['INGCO','Product: Cordless drill','SKU: CD123','Wood: 25 mm','Nett price: R1000']);const result=await analyzePdfPage({pageNumber:1,embeddedText,pagePreviewDataUrl:'data:image/jpeg;base64,AA=='},{request:async()=>{calls++;throw Error('OCR must not run');}});assert.equal(calls,0);assert.equal(result.ocrText,'');assert.equal(result.analysis.sku.value,'CD123');assert.equal(result.analysis.nettPrice.value,'1000');assert.equal(result.analysis.nettPrice.source,'EMBEDDED_TEXT');});
test('multi-product PDF: separate evidence, no merged specifications or auto-combination',async()=>{const text=await read(['Product: Drill','SKU: DR1','Wood: 25 mm','Product: Saw','SKU: SA2','Wood: 210 mm']);const a=heuristicPageAnalysis(text,'',1);assert.equal(a.productCount,2);assert.equal(a.detectedProducts.length,2);assert.match(a.detectedProducts[0].sourceText,/25 mm/);assert.doesNotMatch(a.detectedProducts[0].sourceText,/210 mm/);assert.deepEqual(a.technicalSpecifications,[]);assert.equal(a.nettPrice.value,'Not found');for(const decision of [null,'SEPARATE_ADVERTS','COMBINED_ADVERT','MANUAL_REVIEW'])assert.ok(coreReviewIssues(a,{multiProductDecision:decision,pricingValid:true}).length);});
test('sale PDF: original WAS/NOW retained and NOW controls final sale price',async()=>{const text=await read(['INGCO','Product: Cordless drill','SKU: DR1','Wood: 25 mm','WAS R2799','NOW R2499']);const a=heuristicPageAnalysis(text,'',1);assert.equal(a.wasPrice.value,'2799');assert.equal(a.promotionalPrice.value,'2499');const original=extractedPricing(a);const before=JSON.stringify(original);const result=resolvePricing(original,pricingInputSchema.parse({method:'SALE',wasPrice:original.wasPrice.value,nowPrice:original.sellingPrice.value}));assert.equal(result.finalSellingPrice,2499);assert.equal(result.wasPrice,2799);assert.equal(JSON.stringify(original),before);const ad=advertSchema.parse({...TEST_ADVERT,originalImageUrl:'fixture',useOriginalImage:true,pricingMethod:'SALE',wasPrice:result.wasPrice,sellingPrice:String(result.finalSellingPrice)});assert.equal(ad.nowPrice,2499);assert.equal(ad.wasPrice,2799);assert.equal(ad.pricingMethod,'SALE');});
test('scanned saw regression: no inferred SKU or price; only page-specific exclusions',()=>{const a=heuristicPageAnalysis('','INGCO\nProduct: Brushless cordless reciprocating saw\nWood: 210 mm\nMetal: 12 mm\nBattery and charger sold separately',1);assert.equal(a.nettPrice.value,'Not found');assert.equal(a.sku.value,'Not found');assert.equal(a.powerInclusion.batteryIncluded,'NO');assert.equal(a.powerInclusion.chargerIncluded,'NO');assert.equal(a.technicalSpecifications[0].source,'OCR');});
test('reloading a partially failed import preserves its completed page',()=>{const {hydratePdfPage}=require('../.test-dist/lib/pdf-review-state');const a=heuristicPageAnalysis('Product: Cordless drill\nSKU: DR1\nWood: 25 mm','',1);const pages=[{pageNumber:1,analysisJson:JSON.stringify(a),status:'REVIEW_REQUIRED',pricingJson:'{}'},{pageNumber:2,analysisJson:'{}',status:'ANALYSIS_FAILED'}].map(hydratePdfPage);assert.equal(pages[0].analysis.sku.value,'DR1');assert.equal(pages[1].analysis,undefined);assert.match(pages[1].error,/Other completed pages/);});
test('PDF mock mode never sends page data to the live provider',async()=>{const old=process.env.AI_MODE;process.env.AI_MODE='mock';try{let calls=0;const result=await analyzePdfPage({pageNumber:1,embeddedText:'',pagePreviewDataUrl:'data:image/jpeg;base64,AA=='},{request:async()=>{calls++;throw Error('Unexpected external request');}});assert.equal(calls,0);assert.equal(result.method,'HEURISTIC');}finally{if(old===undefined)delete process.env.AI_MODE;else process.env.AI_MODE=old;}});
