import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, FilePenLine, Package, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { prisma } from "@/lib/prisma"; import { getCurrentUser, canReviewAdvert } from "@/lib/user-role"; import { formatZar } from "@/lib/format-price";

export async function Dashboard() {
  const user=getCurrentUser(); const own=user.role==="STAFF"?{createdByUserId:user.id}:{};
  const [drafts,awaiting,changes,approved,products,recent,activity]=await Promise.all([
    prisma.advertisement.count({where:{...own,status:"DRAFT"}}),prisma.advertisement.count({where:{...own,status:"AWAITING_APPROVAL"}}),prisma.advertisement.count({where:{...own,status:"CHANGES_REQUESTED"}}),prisma.advertisement.count({where:{...own,status:"APPROVED"}}),prisma.product.count({where:{active:true}}),prisma.advertisement.findMany({where:own,orderBy:{updatedAt:"desc"},take:5}),prisma.auditLog.findMany({orderBy:{createdAt:"desc"},take:5})]);
  const today=new Date();today.setHours(0,0,0,0);const week=new Date(today);week.setDate(week.getDate()+7);const month=new Date(today.getFullYear(),today.getMonth(),1);const [scheduledToday,scheduledWeek,publishedMonth,failedPosts]=await Promise.all([prisma.socialPost.count({where:{scheduledAt:{gte:today,lt:new Date(today.getTime()+86400000)}}}),prisma.socialPost.count({where:{scheduledAt:{gte:today,lt:week}}}),prisma.socialPost.count({where:{publishedAt:{gte:month}}}),prisma.socialPost.count({where:{status:{in:["FAILED","PARTIALLY_PUBLISHED"]}}})]);
  const metrics=[{label:"Scheduled today",value:scheduledToday,note:`${scheduledWeek} this week`,icon:Clock3},{label:"Published this month",value:publishedMonth,note:"Across channels",icon:CheckCircle2},{label:"Publishing issues",value:failedPosts,note:"Retry required",icon:RefreshCw},{label:"Approved",value:approved,note:"Ready to publish",icon:ShieldCheck},{label:"Products",value:products,note:"Active library",icon:Package}];
  return <div className="dashboard-grid"><section className="hero-panel"><div><span className="section-kicker">TOOLHUB SOCIAL STUDIO</span><h2>Daily production.<br/><em>Brand controlled.</em></h2><p>Select a reusable product, create a snapshot advert, and send it through manager approval—all without changing the approved template.</p><div className="hero-actions"><Link href="/create" className="primary-button"><Plus size={20}/> Create Advert</Link><Link href="/products/new" className="secondary-button"><Package size={18}/> Add Product</Link>{canReviewAdvert(user.role)&&<Link href="/approvals" className="secondary-button"><ShieldCheck size={18}/> Review Approvals</Link>}</div></div><div className="hero-art" aria-hidden="true"><div className="poster-mini"><b>#LoveTools</b><span>YOUR PRODUCT</span><strong>R2 499</strong><i/></div><div className="orange-orbit"/></div></section>
  <section className="metrics-grid phase2-metrics">{metrics.map(({label,value,note,icon:Icon})=><article className="metric-card" key={label}><div className="metric-icon"><Icon size={20}/></div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
  <section className="activity-panel panel"><div className="panel-heading"><span className="section-kicker">RECENT ADVERTS</span><h3>Your latest production</h3></div>{recent.length?<div className="recent-list">{recent.map(advert=><article key={advert.id}><div><strong>{advert.productName}</strong><span>{advert.sku} · {formatZar(advert.sellingPrice)}</span></div><span className={`status-badge ${advert.status.toLowerCase()}`}>{advert.status.replaceAll("_"," ")}</span><Link href={`/adverts/${advert.id}`}>{["DRAFT","CHANGES_REQUESTED"].includes(advert.status)?"Continue Editing":"View"} <ArrowRight size={14}/></Link></article>)}</div>:<div className="empty-state"><FilePenLine size={28}/><h4>No adverts yet</h4><p>Your saved drafts will appear here.</p></div>}</section>
  <aside className="rules-panel panel"><ShieldCheck size={28}/><span className="section-kicker">RECENT ACTIVITY</span><h3>Accountability built in.</h3>{activity.length?<ul>{activity.map(item=><li key={item.id}>{item.userName||"System"} · {item.action.replaceAll("_"," ")}</li>)}</ul>:<p>Workflow events will appear here.</p>}</aside></div>;
}
