"use client";
import { emptyPower, powerStatement, type PowerInclusion } from "@/lib/power-inclusion";
export function PowerInclusionReview({value,onChange}:{value?:PowerInclusion;onChange:(p:PowerInclusion)=>void}){
 const p=value??emptyPower(); const edit=(patch:Partial<PowerInclusion>)=>onChange({...p,...patch,manuallyConfirmed:false,inclusionConfidence:"LOW",inclusionSource:"USER",confirmedByUserId:null});
 return <section className="import-pricing" aria-label="Power and included items"><h3>POWER / INCLUDED ITEMS</h3><p>{powerStatement(p)||"Confirmation required"}</p>
 <div className="sale-price-fields">{([['batteryIncluded','Battery included'],['chargerIncluded','Charger included']] as const).map(([key,label])=><label className="pdf-review-field" key={key}><span>{label}</span><select value={p[key]} onChange={e=>edit({[key]:e.target.value,accessoryCondition:"STATED"} as Partial<PowerInclusion>)}><option value="NOT_STATED">Not stated</option><option value="YES">Yes</option><option value="NO">No</option></select></label>)}
 <label className="pdf-review-field"><span>Battery quantity</span><input type="number" min="1" max="100" value={p.batteryQuantity??""} onChange={e=>edit({batteryQuantity:e.target.value?Number(e.target.value):null})}/></label>
 <label className="pdf-review-field"><span>Battery capacity</span><input value={p.batteryCapacity} placeholder="e.g. 2.0Ah" onChange={e=>edit({batteryCapacity:e.target.value})}/></label></div>
 <label className="pdf-review-field"><span>Accessory condition</span><select value={p.accessoryCondition} onChange={e=>edit({accessoryCondition:e.target.value as PowerInclusion['accessoryCondition'],...(["BARE_TOOL","SOLD_SEPARATELY"].includes(e.target.value)?{batteryIncluded:"NO",chargerIncluded:"NO",batteryQuantity:null,batteryCapacity:""}:{})})}><option value="NOT_STATED">Not stated / confirmation required</option><option value="UNCLEAR">Unclear / confirmation required</option><option value="STATED">Included / excluded as specified</option><option value="SOLD_SEPARATELY">Sold separately</option><option value="BARE_TOOL">Bare tool only</option></select></label>
 {(['includedAccessories','excludedAccessories'] as const).map(key=><label className="pdf-review-field" key={key}><span>{key==='includedAccessories'?'Included accessories':'Excluded accessories'}</span><textarea value={p[key].join('\n')} onChange={e=>edit({[key]:e.target.value.split('\n')})}/></label>)}
 <p>Confidence: {p.inclusionConfidence} · {p.inclusionSource}{p.manuallyConfirmed?' · Manually confirmed':''}</p><p>PDF evidence: {p.inclusionSourceText||'Not stated'}</p>
 <button className="secondary-button" type="button" onClick={()=>onChange({...p,manuallyConfirmed:true,inclusionConfidence:"HIGH",inclusionSource:"USER"})}>Confirm power / included items</button><p>Unconfirmed or unclear wording is omitted from the advert.</p></section>;
}
