"use client";
import { ChangeEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ImagePlus, Loader2, Save, ShieldCheck } from "lucide-react";
import type { ProductInput } from "@/lib/product";
import { validateProductImageUpload } from "@/lib/product-image";

const EMPTY: ProductInput = { sku:"", barcode:"", brand:"INGCO", productName:"", category:"Tools", primarySpecification:"", secondarySpecification:"", feature01:"", feature02:"", keyBenefit:"", normalPrice:null, currentPrice:0, websiteUrl:"https://www.toolhub.co.za", originalImageUrl:"", processedImageUrl:"", backgroundRemovalStatus:"PENDING", active:true };
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="field"><span>{label}</span>{children}</label>; }

export function ProductForm({ product, returnToAdvert=false }: { product?: (ProductInput & {id:string}); returnToAdvert?: boolean }) {
  const [data,setData]=useState<ProductInput>(product || EMPTY); const [saving,setSaving]=useState(false); const [processing,setProcessing]=useState(false); const [notice,setNotice]=useState(""); const [existingId,setExistingId]=useState(""); const router=useRouter();
  const set=(key:keyof ProductInput,value:unknown)=>setData(current=>({...current,[key]:value}));
  const image=async(event:ChangeEvent<HTMLInputElement>)=>{ const file=event.target.files?.[0]; if(!file)return; const error=validateProductImageUpload(file); if(error){setNotice(error);return;} setProcessing(true);setNotice("Removing background…"); const originalImageUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)}); setData(current=>({...current,originalImageUrl,processedImageUrl:"",backgroundRemovalStatus:"PROCESSING"})); try{const form=new FormData();form.append("image",file);const response=await fetch("/api/product-images/remove-background",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);setData(current=>({...current,originalImageUrl,processedImageUrl:result.processedImageUrl,backgroundRemovalStatus:"COMPLETE"}));setNotice("Transparent product image ready.");}catch(e){set("backgroundRemovalStatus","FAILED");setNotice(e instanceof Error?e.message:"Background removal failed");}finally{setProcessing(false);event.target.value="";}};
  const save=async()=>{setSaving(true);setNotice("");setExistingId("");const response=await fetch(product?`/api/products/${product.id}`:"/api/products",{method:product?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();setSaving(false);if(!response.ok){setNotice(result.error||"Unable to save product");setExistingId(result.existing?.id||"");return;}router.push(returnToAdvert?`/create?productId=${result.id}`:"/products");router.refresh();};
  return <section className="form-panel product-form"><div className="form-intro"><div className="step-badge">P</div><div><span className="section-kicker">PRODUCT RECORD</span><h2>{product?"Edit reusable product":"Add a reusable product"}</h2><p>Specifications and transparent imagery can be reused across adverts.</p></div></div>
    <div className="form-section"><div className="form-section-heading"><span>BASIC</span></div><div className="field-grid two"><Field label="SKU *"><input value={String(data.sku)} onChange={e=>set("sku",e.target.value.toUpperCase())}/></Field><Field label="Barcode"><input value={String(data.barcode||"")} onChange={e=>set("barcode",e.target.value)}/></Field><Field label="Brand *"><input value={String(data.brand)} onChange={e=>set("brand",e.target.value)}/></Field><Field label="Category *"><input value={String(data.category)} onChange={e=>set("category",e.target.value)}/></Field></div><Field label="Product Name *"><input value={String(data.productName)} onChange={e=>set("productName",e.target.value)}/></Field></div>
    <div className="form-section"><div className="form-section-heading"><span>SPECIFICATIONS</span></div><Field label="Primary Specification *"><input value={String(data.primarySpecification)} onChange={e=>set("primarySpecification",e.target.value)}/></Field><Field label="Secondary Specification"><textarea rows={2} value={String(data.secondarySpecification||"")} onChange={e=>set("secondarySpecification",e.target.value)}/></Field><div className="field-grid two"><Field label="Feature 01"><input value={String(data.feature01||"")} onChange={e=>set("feature01",e.target.value)}/></Field><Field label="Feature 02"><input value={String(data.feature02||"")} onChange={e=>set("feature02",e.target.value)}/></Field></div><Field label="Key Product Benefit"><input value={String(data.keyBenefit||"")} onChange={e=>set("keyBenefit",e.target.value)}/></Field></div>
    <div className="form-section"><div className="form-section-heading"><span>PRICE & WEBSITE</span></div><div className="field-grid two"><Field label="Normal Price"><input inputMode="numeric" value={String(data.normalPrice||"")} onChange={e=>set("normalPrice",e.target.value.replace(/\D/g,""))}/></Field><Field label="Current Selling Price *"><input inputMode="numeric" value={String(data.currentPrice)} onChange={e=>set("currentPrice",e.target.value.replace(/\D/g,""))}/></Field></div><Field label="Product URL"><input type="url" value={String(data.websiteUrl||"")} onChange={e=>set("websiteUrl",e.target.value)}/></Field></div>
    <div className="form-section"><div className="form-section-heading"><span>PRODUCT IMAGE</span><small>Saved once, reused on future adverts.</small></div><label className={`upload-zone ${data.originalImageUrl?"ready":""}`}><input type="file" accept="image/png,image/jpeg,image/webp" disabled={processing} onChange={image}/>{data.originalImageUrl?<><div className="upload-comparison"><figure><img src={String(data.originalImageUrl)} alt="Original"/><figcaption>Original</figcaption></figure>{data.processedImageUrl&&<figure className="transparent-thumb"><img src={String(data.processedImageUrl)} alt="Processed transparent"/><figcaption>Transparent</figcaption></figure>}</div><strong>{processing?"Removing background…":"Replace product image"}</strong>{processing?<Loader2 className="spin"/>:<ImagePlus/>}</>:<><ImagePlus/><div><strong>Upload original product image</strong><span>Background removal runs automatically.</span></div></>}</label><label className="toggle-row"><input type="checkbox" checked={Boolean(data.active)} onChange={e=>set("active",e.target.checked)}/><span>Active product</span></label></div>
    {notice&&<div className="notice error" role="status"><span>{notice}</span>{existingId&&<div className="duplicate-actions"><Link href={`/products/${existingId}/edit`}>Open existing product</Link><button type="button" onClick={()=>{setNotice("");setExistingId("")}}>Cancel</button></div>}</div>}<div className="form-actions"><button className="primary-button" type="button" onClick={save} disabled={saving||processing}>{saving?<Loader2 className="spin"/>:<Save size={18}/>} Save Product</button></div>
  </section>;
}
