export const PLAN_STATUSES=["PLANNING_DRAFT","AWAITING_PLAN_APPROVAL","PLAN_APPROVED","ACTIVATED","CANCELLED"] as const;
export const PLAN_ITEM_STATUSES=["SUGGESTED","READY","BLOCKED","SCHEDULED","CANCELLED","SKIPPED"] as const;
export const PRIORITY_WEIGHTS:Record<string,number>={LOW:-10,NORMAL:0,HIGH:25,URGENT:50};
export type PlannerAdvert={id:string;status:string;sku:string;productName:string;category:string;campaignType:string;approvedAt:Date|null;createdAt:Date;planningPriority:string;validFrom:Date|null;validUntil:Date|null};
export type PlannerHistory={advertisementId:string;sku:string;category:string;campaignType:string;channelId:string;scheduledAt:Date;status:string};
export type PlannerRules={timezone:string;postsPerWeek:number;preferredDays:number[];preferredTime:string;sameSkuCooldownDays:number;sameAdvertCooldownDays:number;maxSpecialsPerWeek:number;maxBackInStockPerWeek:number;categoryBalancing:boolean;campaignBalancing:boolean};
export type PlannerSuggestion={advertisementId:string;channelId:string;plannedAt:Date;score:number;reason:string;warnings:string[];manualPinned:boolean};
const DAY=86400000;const special=(value:string)=>/special|clearance/i.test(value),back=(value:string)=>/back.in.stock/i.test(value);
export function plannerEligible(advert:PlannerAdvert,at:Date){return advert.status==="APPROVED"&&(!advert.validFrom||at>=advert.validFrom)&&(!advert.validUntil||at<=advert.validUntil)}
export function scoreAdvert(advert:PlannerAdvert,at:Date,history:PlannerHistory[],rules:PlannerRules,selected:PlannerAdvert[]=[]){const warnings:string[]=[];let score=100+(PRIORITY_WEIGHTS[advert.planningPriority]||0);const sameSku=history.filter(x=>x.sku===advert.sku).sort((a,b)=>b.scheduledAt.getTime()-a.scheduledAt.getTime())[0],sameAdvert=history.filter(x=>x.advertisementId===advert.id).sort((a,b)=>b.scheduledAt.getTime()-a.scheduledAt.getTime())[0];if(sameSku){const days=(at.getTime()-sameSku.scheduledAt.getTime())/DAY;if(days<rules.sameSkuCooldownDays){score-=1000;warnings.push(`SKU posted ${Math.floor(days)} days ago; cooldown is ${rules.sameSkuCooldownDays} days`) }else score+=Math.min(days,60)}if(sameAdvert&&(at.getTime()-sameAdvert.scheduledAt.getTime())/DAY<rules.sameAdvertCooldownDays){score-=500;warnings.push("Advert is inside its repeat cooldown")};if(advert.approvedAt)score+=Math.max(0,30-Math.floor((at.getTime()-advert.approvedAt.getTime())/DAY));if(rules.categoryBalancing&&selected.some(x=>x.category===advert.category))score-=20*selected.filter(x=>x.category===advert.category).length;if(rules.campaignBalancing&&selected.some(x=>x.campaignType===advert.campaignType))score-=18*selected.filter(x=>x.campaignType===advert.campaignType).length;return{score,warnings}}
export function weekSlots(weekStart:Date,rules:PlannerRules){const [hour,minute]=rules.preferredTime.split(":").map(Number);return rules.preferredDays.slice(0,rules.postsPerWeek).map(day=>{const date=new Date(weekStart);date.setUTCDate(date.getUTCDate()+((day-date.getUTCDay()+7)%7));date.setUTCHours(hour-2,minute,0,0);return date})}
export function generateDeterministicPlan(input:{adverts:PlannerAdvert[];history:PlannerHistory[];channelIds:string[];weekStart:Date;rules:PlannerRules;pinned?:PlannerSuggestion[]}){const suggestions=[...(input.pinned||[])],selected:PlannerAdvert[]=[];let specials=0,backs=0;for(const channelId of input.channelIds){for(const at of weekSlots(input.weekStart,input.rules)){if(suggestions.some(x=>x.channelId===channelId&&x.plannedAt.getTime()===at.getTime()))continue;const usedSkus=new Set(suggestions.filter(x=>x.channelId===channelId).map(x=>input.adverts.find(a=>a.id===x.advertisementId)?.sku));const ranked=input.adverts.filter(a=>plannerEligible(a,at)&&!usedSkus.has(a.sku)).map(advert=>({advert,...scoreAdvert(advert,at,input.history.filter(x=>x.channelId===channelId),input.rules,selected)})).filter(x=>x.score>-500).filter(x=>!(special(x.advert.campaignType)&&specials>=input.rules.maxSpecialsPerWeek)).filter(x=>!(back(x.advert.campaignType)&&backs>=input.rules.maxBackInStockPerWeek)).sort((a,b)=>b.score-a.score||a.advert.sku.localeCompare(b.advert.sku));const next=ranked[0];if(!next)continue;selected.push(next.advert);if(special(next.advert.campaignType))specials++;if(back(next.advert.campaignType))backs++;suggestions.push({advertisementId:next.advert.id,channelId,plannedAt:at,score:next.score,reason:[next.advert.planningPriority!=="NORMAL"?`${next.advert.planningPriority.toLowerCase()} priority approved advert`:"approved content not recently repeated",input.rules.categoryBalancing?`balances category mix (${next.advert.category})`:"deterministic eligibility",input.rules.campaignBalancing?`supports campaign variety (${next.advert.campaignType})`:"campaign rules disabled"].join("; "),warnings:next.warnings,manualPinned:false})}}const required=input.channelIds.length*input.rules.postsPerWeek;return{suggestions:suggestions.sort((a,b)=>a.plannedAt.getTime()-b.plannedAt.getTime()),required,filled:suggestions.length,gaps:Math.max(0,required-suggestions.length)}}
export function activationChecks(input:{advertStatus:string;channelActive:boolean;publishingEnabled:boolean;artworkUrl:string;caption:string;captionState:string;plannedAt:Date;now:Date;duplicate:boolean;conflict:boolean;validUntil:Date|null}){const reasons:string[]=[];if(input.advertStatus!=="APPROVED")reasons.push("Advertisement is not APPROVED");if(!input.channelActive||!input.publishingEnabled)reasons.push("Channel is inactive or publishing disabled");if(!input.artworkUrl)reasons.push("Final artwork is missing");if(!input.caption.trim()||input.captionState!=="READY")reasons.push("Caption is not READY");if(input.plannedAt<=input.now)reasons.push("Planned time is not in the future");if(input.duplicate)reasons.push("Duplicate schedule exists");if(input.conflict)reasons.push("Channel/time conflict exists");if(input.validUntil&&input.plannedAt>input.validUntil)reasons.push("Campaign expires before planned time");return{ok:reasons.length===0,reasons}}
